// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-wVKOmANxeMtec-OGB-n3ukYhuRBNTy8',
    appId: '1:738173339281:web:a65cd4e6ed9583a6646130',
    messagingSenderId: '738173339281',
    projectId: 'rapidaid-project',
    authDomain: 'rapidaid-project.firebaseapp.com',
    storageBucket: 'rapidaid-project.firebasestorage.app',
    measurementId: 'G-ZKJCP8Q3CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ5-Uq375zg04aEbRhHi-TY7x9xgJenEM',
    appId: '1:738173339281:android:8f10f582e5338ba0646130',
    messagingSenderId: '738173339281',
    projectId: 'rapidaid-project',
    storageBucket: 'rapidaid-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjfSwN5fUe1dDh50KmuCcqDQmkvXsh7CE',
    appId: '1:738173339281:ios:4b9b31e6834977a2646130',
    messagingSenderId: '738173339281',
    projectId: 'rapidaid-project',
    storageBucket: 'rapidaid-project.firebasestorage.app',
    iosBundleId: 'com.example.rapidaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjfSwN5fUe1dDh50KmuCcqDQmkvXsh7CE',
    appId: '1:738173339281:ios:4b9b31e6834977a2646130',
    messagingSenderId: '738173339281',
    projectId: 'rapidaid-project',
    storageBucket: 'rapidaid-project.firebasestorage.app',
    iosBundleId: 'com.example.rapidaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-wVKOmANxeMtec-OGB-n3ukYhuRBNTy8',
    appId: '1:738173339281:web:24c41c1321d392d7646130',
    messagingSenderId: '738173339281',
    projectId: 'rapidaid-project',
    authDomain: 'rapidaid-project.firebaseapp.com',
    storageBucket: 'rapidaid-project.firebasestorage.app',
    measurementId: 'G-FLJ8XJ2XDF',
  );
}
