name: rapidaid
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_bloc: ^9.1.0
  go_router: ^14.8.1
  intl: ^0.20.2
  firebase_data_connect: ^0.1.0
  camera: ^0.11.1
  image_picker: ^1.1.2
  google_maps_flutter: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica Black Condensed Oblique.otf
        - asset: assets/fonts/Helvetica Black Condensed.otf
        - asset: assets/fonts/Helvetica Black Oblique.otf
        - asset: assets/fonts/helvetica black.otf
        - asset: assets/fonts/Helvetica Bold Condensed.otf
        - asset: assets/fonts/Helvetica Bold Narrow Oblique.otf
        - asset: assets/fonts/Helvetica Condensed Bold Oblique.otf
        - asset: assets/fonts/Helvetica Condensed Oblique.otf
        - asset: assets/fonts/Helvetica Condensed Regular.ttf
        - asset: assets/fonts/Helvetica Extra Compressed Regular.otf
        - asset: assets/fonts/Helvetica Inserat Roman.otf
        - asset: assets/fonts/Helvetica Light Condensed.otf
        - asset: assets/fonts/Helvetica Roman.ttf
        - asset: assets/fonts/Helvetica Rounded Black.otf
        - asset: assets/fonts/Helvetica Rounded Bold Oblique.otf
        - asset: assets/fonts/Helvetica Rounded Bold.otf
        - asset: assets/fonts/Helvetica Rounded Condensed Bold.otf
        - asset: assets/fonts/Helvetica Rounded LT Std Bold Condensed Oblique.otf
        - asset: assets/fonts/Helvetica Ultra Compressed.otf
        - asset: assets/fonts/helvetica_condensed.ttf
        - asset: assets/fonts/Helvetica-Bold Oblique.ttf
        - asset: assets/fonts/Helvetica-Bold.ttf
        - asset: assets/fonts/helvetica-compressed.otf
        - asset: assets/fonts/helvetica-light.ttf
        - asset: assets/fonts/Helvetica-LightOblique.ttf
        - asset: assets/fonts/Helvetica-Narrow Bold.ttf
        - asset: assets/fonts/Helvetica-Narrow Roman.ttf
        - asset: assets/fonts/Helvetica-Narrow-Oblique.ttf
        - asset: assets/fonts/Helvetica-Oblique.ttf
        - asset: assets/fonts/helvetica-rounded-bold.otf
        - asset: assets/fonts/Helvetica.ttf

    - family: Chopra
      fonts:
        - asset: assets/fonts/Chopra-BF67dfa2ad472cb.ttf
        - asset: assets/fonts/Chopra-Extended-BF67dfa2ad3db8a.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
